### PR TITLE
many *small* things, add echo command

### PR DESCRIPTION
**Pull request by khanhmuy**
- add "echo" command
- add some aliases for the "avatar" command
- add "*nice*" message when roll result is 69

### CODE REVIEW

**Comment by khanhmuy** [comment]
uhm so the echo command is ~~kinda~~ broken

**Comment by CallMeEchoCodes** [comment]
> 
> 
> uhm so the echo command is ~kinda~ broken

Is it still good to merge?

**Comment by CallMeEchoCodes** [comment]
Update 2.0.0 rewrote the bot making this outdated.

**Comment by khanhmuy** [comment]
trol

**Pull request closed without merging**
